//#include "UnityCG.cginc"

#pragma kernel DepthRender

Texture2D<float4> _DepthTexture;
RWTexture2D<float4> _OutputTexture;
float camFarPlane;
float camNearPlane;
RWStructuredBuffer<float> sampleDepth;


    
[numthreads(8, 8, 1)]
void DepthRender(uint3 uv : SV_DispatchThreadID)
{
    _OutputTexture[uv.xy] = _DepthTexture[uv.xy] * camFarPlane;  
    //float depth = Linear01Depth(_DepthTexture[float2(960, 540)].r);
    sampleDepth[0] = depth;
}